SELECT * FROM dados_mutuarios;
SELECT * FROM IDS;
SELECT * FROM emprestimos;
SELECT * FROM historicos_banco;

SELECT * FROM dados_mutuarios A 
INNER JOIN historicos_banco B 
ON A.PERSON_ID = B.CB_ID;

SELECT ID_PESSOAL FROM dados_mutuarios
WHERE ID_PESSOAL is null;

SELECT ID_CB, COUNT(*) c FROM IDs
GROUP BY ID_CB
HAVING c > 1;

ALTER TABLE emprestimos RENAME COLUMN 
loan_status TO STATUS_EMPRESTIMO; 

SELECT IDADE, COUNT(*) C FROM DADOS_MUTUARIOS
WHERE IDADE IS NULL
GROUP BY IDADE;

SELECT COUNT(*) C FROM DADOS_MUTUARIOS
WHERE ID_PESSOAL AND IDADE AND RENDIMENTO AND PROPRIEDADE_CASA AND TAMANHO_PROP IS NULL;
